"""empty message

Revision ID: 3da908a0ed34
Revises: 76fdf3992bab
Create Date: 2022-01-29 09:30:43.125166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da908a0ed34'
down_revision = '76fdf3992bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
