"""empty message

Revision ID: 4b783ce3b210
Revises: 
Create Date: 2022-01-22 11:39:29.542755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b783ce3b210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_files', sa.String(), nullable=False))
    op.drop_column('item', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('item', 'image_files')
    # ### end Alembic commands ###
