"""empty message

Revision ID: 51b4aa38d644
Revises: 57c1086a0a6b
Create Date: 2022-01-24 10:31:38.702412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b4aa38d644'
down_revision = '57c1086a0a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('item_filters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
